# Generated by Django 5.1.4 on 2024-12-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bodegas', '0002_initial'),
        ('Libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoproducto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productobodega',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bodegas.bodega'),
        ),
        migrations.AddField(
            model_name='productobodega',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.libro'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='productos',
            field=models.ManyToManyField(through='Bodegas.ProductoBodega', to='Libros.libro'),
        ),
    ]
