# Generated by Django 5.1.3 on 2024-11-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bodegas', '0003_alter_bodega_nivel_stock_productobodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='estado',
            field=models.CharField(choices=[('BA', 'Bacio'), ('OC', 'Ocupado'), ('MT', 'Mantenimiento')], default='BA', max_length=2),
        ),
    ]
