# Generated by Django 5.1.2 on 2024-11-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bodegas', '0004_alter_bodega_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='direction',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
