# Generated by Django 5.1.3 on 2024-12-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bodegas', '0005_alter_bodega_direction_alter_bodega_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='estado',
            field=models.CharField(choices=[('VA', 'Vacio'), ('OC', 'Ocupado'), ('MT', 'Mantenimiento')], default='BA', max_length=2),
        ),
    ]
