# Generated by Django 5.1.3 on 2024-12-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bodegas', '0006_alter_bodega_estado'),
        ('Libros', '0019_rename_camtidad_libro_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='productos',
            field=models.ManyToManyField(through='Bodegas.ProductoBodega', to='Libros.libro'),
        ),
    ]
