# Generated by Django 5.1.3 on 2024-11-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0002_alter_libro_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
