# Generated by Django 5.1.3 on 2024-11-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0004_libro_editorial_libro_tamano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='tamano',
        ),
        migrations.AddField(
            model_name='libro',
            name='tamaño',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
