# Generated by Django 5.1.3 on 2024-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0005_remove_libro_tamano_libro_tamaño_alter_libro_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='libros'),
        ),
    ]
