# Generated by Django 5.1.2 on 2024-11-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0006_libro_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portada'),
        ),
    ]
