# Generated by Django 5.1.2 on 2024-11-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0007_editorial_alter_libro_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
            ],
        ),
    ]
