# Generated by Django 5.1.3 on 2024-11-14 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0007_alter_libro_portada'),
        ('Libros', '0007_editorial_alter_libro_portada'),
    ]

    operations = [
    ]
