# Generated by Django 5.1.2 on 2024-11-14 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0007_alter_libro_portada'),
        ('Libros', '0008_users'),
    ]

    operations = [
    ]
