# Generated by Django 5.1.3 on 2024-11-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0008_merge_20241113_2108'),
        ('Libros', '0009_merge_0007_alter_libro_portada_0008_users'),
    ]

    operations = [
    ]
