# Generated by Django 5.1.3 on 2024-11-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0012_delete_editorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
