# Generated by Django 5.1.3 on 2024-11-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0015_alter_libro_author'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.users', verbose_name='Author'),
        ),
    ]
