# Generated by Django 5.1.3 on 2024-11-19 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editoriales', '0001_initial'),
        ('Libros', '0016_alter_libro_author'),
        ('Usuarios', '0002_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.users'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editoriales.editorial'),
        ),
    ]
