# Generated by Django 5.1.2 on 2024-11-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0017_alter_libro_author_alter_libro_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='camtidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(upload_to='portada'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tamaño',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(choices=[('Libro', 'Libro'), ('Revista', 'Revista'), ('Enciclopedias', 'Enciclopedias')], max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
