# Generated by Django 5.1.4 on 2024-12-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0019_rename_camtidad_libro_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='tamaño',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
