# Generated by Django 5.1.4 on 2024-12-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0020_alter_libro_tamaño'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estadoLibro',
            field=models.CharField(choices=[('Revision', 'Revisión'), ('Publicado', 'Publicado')], max_length=9, null=True),
        ),
    ]
