# Generated by Django 5.1.4 on 2024-12-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0021_libro_estadolibro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='estadoLibro',
            field=models.CharField(choices=[('Revision', 'Revisión'), ('Publicado', 'Publicado'), ('Denegado', 'Denegado')], max_length=9, null=True),
        ),
    ]
