# Generated by Django 5.1.3 on 2024-11-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0016_alter_libro_author'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
