# Generated by Django 5.1 on 2024-11-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('autor', 'Autor'), ('jefe_bodega', 'Jefe de Bodega')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='Usuarios.rol'),
        ),
    ]
