# Generated by Django 5.1 on 2024-11-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_rol_alter_users_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='id',
        ),
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(choices=[('autor', 'Autor'), ('jefe_bodega', 'Jefe de Bodega')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
