# Generated by Django 5.1.4 on 2024-12-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editoriales', '0002_alter_editorial_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
